version: '3'

services:
  web:
    build: .
    command: python -u app.py
    ports:
      - "5000:5000"
    # command: ["pipenv", "run"]
    volumes:
      - ./:/home/dev/code/
# version: '3'

# services:
#   mongo:
#     image: mongo
#     container_name: mongodb
#     environment:
#       - MONGO_DATA_DIR=/data/db
#       - MONGO_LOG_DIR=/dev/null
#     volumes:
#       - ./data/mongo:/data/db
#     ports:
#         - 27017:27017
#   web:
#     container_name: webapp
#     build: ./app.py
#     command: python -u app.py
#     ports:
#       - "5000:5000"
#     volumes:
#       - .:/todo
    
